# MAIN base
baseURL = "https://thriving-caramel-51cd39.netlify.app"
languageCode = "en-us"
title = "Fala Mais Alto"
theme = "apsho"

# Navigation Bar
[[menu.main]]
    name = "Página Inicial"
    url = "#homepage"
    weight = 1
[[menu.main]]
    name = "Sobre Nós"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "Projetos"
    url = "#faq"
    weight = 3
[[menu.main]]
    name = "Notícias"
    url = "#blog"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Último artigo"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "Política de Privacidade"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Contacto"
    url = "/contact"
    weight = 4

# Footer Address
[params.address]
address = "23 Khan Niketon, Grand Street, NYK."
email = "apsho@example.com"
phone = "+(448) 833 5272 332"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/pg/staticmania"
twitter = "https://twitter.com/static_mania"
github = "https://github.com/StaticMania"

[params]

# Header
logo = "images/logo.png"
fabFormURL = "https://fabform.io/f/zWMBVeW"
googleAnalytics = "UA-175025671-2"

# Footer
copyright1 = "All right reserved"
copyright2 = "Copyright ©  <a href=\"https://staticmania.com/\" target=\"_blank\">StaticMania </a> {year}"

#contact
email = "help@staticmania.com"
